import os

NICE_API_IPIN_PRODUCT_CODE = os.getenv("NICE_API_IPIN_PRODUCT_CODE")
NICE_API_IV_INTEGRATED_PRODUCT_CODE = os.getenv("NICE_API_IV_INTEGRATED_PRODUCT_CODE")
NICE_API_CLIENT_ID = os.getenv("NICE_API_CLIENT_ID")
NICE_API_CLIENT_SECRET = os.getenv("NICE_API_CLIENT_SECRET")
